<?php

namespace GenAI\Container\Util;

use GenAI\Container\Bean\Definition;
use GenAI\Container\Bean\Param;
use GenAI\Container\Exception\ContainerException;

/**
 * Stateless helper that compiles a list of Definition objects into plain PHP
 * source — a file that wires a Container with no reflection at runtime.
 *
 * Normally you do not call this directly: ContainerRegister::dump() /
 * dumpToFile() drive it. Each bean becomes a literal `new \Foo(...)` inside a
 * lazy Closure, so construction is as fast as hand-written code and stays lazy
 * + shared via the container's get().
 *
 * Input is a map/list of Definition objects:
 *
 *   Definition::create('App\\Mailer', array(
 *       Param::dependency('transport', 'App\\Transport'),
 *       Param::value('retries', 3),
 *   ))
 *
 * Argument precedence per constructor param (matches the runtime conventions):
 *   - Param::value(...)      -> the literal is baked in via var_export().
 *   - Param::dependency(...) -> emitted as $c->get('Type').
 *   - Param::parameter(...)  -> emitted as $c->get('Class::name'), a parameter
 *                               the runtime must register on the container.
 *
 * Generated output (PHP 5.3-safe) is a self-populating container subclass:
 *
 *   <?php
 *   namespace Cache;
 *   class Container extends \GenAI\Container\Container {
 *       public function __construct() {
 *           $this->register('App\\Mailer', function (\GenAI\Container\Container $c) {
 *               return new \App\Mailer($c->get('App\\Transport'), 3);
 *           });
 *       }
 *   }
 *   // runtime:  $container = new \Cache\Container();   // ready, no loadCompiled
 *
 * Builds only strings, so it is PHP 5.3-safe and runs under either runtime.
 *
 * Circular dependencies are detected here, at compile time, so the generated
 * file is guaranteed acyclic and the runtime never has to guard against loops.
 *
 * Compatible with PHP 5.3.29.
 */
class Dumper
{
    /**
     * Compile a list of definitions to PHP source for a populate-the-container
     * file.
     *
     * @param Definition[] $definitions Map (id => Definition) or plain list.
     * @param array        $parameters  Map (id => scalar value), baked as
     *                                  constant-returning factories.
     * @return string PHP source, starting with "<?php", returning a Closure.
     * @throws ContainerException If the dependency graph contains a cycle.
     */
    public static function dump($definitions, $parameters = array())
    {
        // Normalise to an id => Definition map (string key wins; numeric key
        // falls back to the class name) so emission and cycle-checking agree.
        $byId = array();
        foreach ($definitions as $key => $def) {
            $id = is_string($key) ? $key : $def->getClass();
            $byId[$id] = $def;
        }

        self::assertAcyclic($byId);

        $body = array();
        foreach ($byId as $id => $def) {
            $body[] = self::dumpDefinition($id, $def);
        }
        foreach ($parameters as $id => $value) {
            $body[] = self::dumpParameter($id, $value);
        }

        $lines = array();
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'namespace Cache;';
        $lines[] = '';
        $lines[] = '// Generated by GenAI\\Container\\Util\\Dumper - do not edit by hand.';
        $lines[] = '// The compiled container: `new \\Cache\\Container()` is ready to use.';
        $lines[] = '';
        $lines[] = 'class Container extends \\GenAI\\Container\\Container';
        $lines[] = '{';
        $lines[] = '    public function __construct()';
        $lines[] = '    {';
        if (!empty($body)) {
            $lines[] = implode("\n", $body);
        }
        $lines[] = '    }';
        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }

    /**
     * Assert the dependency graph has no cycles, throwing with the offending
     * chain if it does. Only Param::dependency edges count — baked values and
     * runtime parameters are leaves. Edges to ids that are not themselves
     * declared beans are ignored (they resolve to parameters or are external).
     *
     * @param Definition[] $byId id => Definition.
     * @throws ContainerException On the first cycle found.
     */
    private static function assertAcyclic($byId)
    {
        $edges = array();
        foreach ($byId as $id => $def) {
            $deps = array();
            if ($def->isFactory()) {
                $deps[] = $def->getFactoryService(); // a factory bean depends on its service
            }
            foreach ($def->getParams() as $param) {
                if (!$param->hasValue()) {
                    $type = $param->getType();
                    if (!empty($type)) {
                        $deps[] = $type;
                    }
                }
            }
            $edges[$id] = $deps;
        }

        $state = array(); // id => 1 on current path, 2 fully explored
        foreach ($edges as $id => $deps) {
            if (!isset($state[$id])) {
                self::walkForCycle($id, $edges, $state, array());
            }
        }
    }

    /**
     * Depth-first walk that throws on a back-edge to a node already on the
     * current path.
     *
     * @param string   $id
     * @param array    $edges  id => list of dependency ids.
     * @param array    $state  By-ref colour map.
     * @param string[] $chain  Ids on the current path (by value per branch).
     * @return void
     * @throws ContainerException
     */
    private static function walkForCycle($id, $edges, &$state, $chain)
    {
        $state[$id] = 1;
        $chain[] = $id;

        foreach ($edges[$id] as $dep) {
            if (!isset($edges[$dep])) {
                continue; // not a declared bean — a parameter or external leaf
            }
            if (isset($state[$dep]) && $state[$dep] === 1) {
                $cycle = array_slice($chain, array_search($dep, $chain, true));
                $cycle[] = $dep;
                throw new ContainerException(sprintf(
                    'Circular dependency detected at compile time: %s',
                    implode(' -> ', $cycle)
                ));
            }
            if (!isset($state[$dep])) {
                self::walkForCycle($dep, $edges, $state, $chain);
            }
        }

        $state[$id] = 2;
    }

    /**
     * Render one `$c->register(...)` call.
     *
     * @param string     $id
     * @param Definition $def
     * @return string
     */
    private static function dumpDefinition($id, Definition $def)
    {
        // Scope for unbaked scalar params is the class, or the bean id when this
        // is a factory bean (no class).
        $scope = $def->getClass() !== null ? $def->getClass() : $id;

        $args = array();
        foreach ($def->getParams() as $param) {
            $args[] = self::dumpArg($scope, $param);
        }
        $argList = implode(', ', $args);

        if ($def->isFactory()) {
            // $c->get('FactoryService')->factoryMethod(args)
            $build = '$c->get(' . var_export($def->getFactoryService(), true) . ')->'
                   . $def->getFactoryMethod() . '(' . $argList . ')';
        } else {
            $build = 'new \\' . ltrim($def->getClass(), '\\') . '(' . $argList . ')';
        }

        $idLiteral = var_export($id, true);

        return '    $this->register(' . $idLiteral . ', function (\\GenAI\\Container\\Container $c) {' . "\n"
             . '        return ' . $build . ';' . "\n"
             . '    });';
    }

    /**
     * Render one `$c->register(...)` call for a scalar parameter — a shared
     * factory that just returns the baked literal.
     *
     * @param string $id
     * @param mixed  $value
     * @return string
     */
    private static function dumpParameter($id, $value)
    {
        $idLiteral = var_export($id, true);
        $literal   = var_export($value, true);

        return '    $this->register(' . $idLiteral . ', function (\\GenAI\\Container\\Container $c) {' . "\n"
             . '        return ' . $literal . ';' . "\n"
             . '    });';
    }

    /**
     * Render one constructor argument expression.
     *
     * @param string $class
     * @param Param  $param
     * @return string
     */
    private static function dumpArg($class, Param $param)
    {
        // A baked literal wins (Param::value); null is honoured.
        if ($param->hasValue()) {
            return var_export($param->getValue(), true);
        }

        // A class/interface dependency: fetch the other bean by its type id.
        $type = $param->getType();
        if (!empty($type)) {
            return '$c->get(' . var_export($type, true) . ')';
        }

        // A scalar the scanner left unbaked: a container parameter, scoped to
        // this class, that the runtime is expected to register before use.
        return '$c->get(' . var_export($class . '::' . $param->getName(), true) . ')';
    }
}
