<?php

// Generated by GenAI\Container\Util\Dumper - do not edit by hand.
// Returns a Closure that populates a GenAI\Container\Container.
// require this file, then call the Closure with your container.

return function (\GenAI\Container\Container $c) {
    $c->register('UserController', function (\GenAI\Container\Container $c) {
        return new \UserController($c->get('UserRepository'), 25);
    });
    $c->register('UserRepository', function (\GenAI\Container\Container $c) {
        return new \UserRepository($c->get('Pdo_Stub'));
    });
    $c->register('Pdo_Stub', function (\GenAI\Container\Container $c) {
        return new \Pdo_Stub($c->get('Pdo_Stub::dsn'));
    });
    $c->register('Pdo_Stub::dsn', function (\GenAI\Container\Container $c) {
        return 'mysql:host=localhost;dbname=app';
    });
};
