<?php

namespace GenAI\Container;

use GenAI\Container\Exception\ContainerException;
use GenAI\Container\Exception\NotFoundException;
use Psr\Container\ContainerInterface;

/**
 * A PSR-11 dependency-injection container — the runtime half.
 *
 * It serves objects from compiled factories (loaded from the file the Dumper
 * wrote) and never reflects on a Definition to build anything. Declaring beans
 * is a build-time concern that lives in ContainerRegister, not here.
 *
 * Every entry is a singleton: a factory runs at most once and its result is
 * cached. If something must not be shared, it does not belong in the container.
 *
 * Build-time declaration (beans and parameters) happens elsewhere:
 *
 *   $register = new ContainerRegister();
 *   $register->set('App\\UserController', Definition::create('App\\UserController', array(
 *       Param::dependency('repo', 'App\\UserRepository'),
 *       Param::value('pageSize', 25),
 *   )));
 *   $register->setParameter('App\\Pdo::dsn', 'mysql:host=localhost;dbname=app');
 *   $register->dumpToFile(__DIR__ . '/cache/container.php');
 *
 * Runtime — load compiled factories, resolve. Everything (beans and parameters)
 * comes from the dump; the runtime container has no declaration methods:
 *
 *   $c = new Container();
 *   $c->loadCompiled(__DIR__ . '/cache/container.php');
 *   $controller = $c->get('App\\UserController');   // built from the dump, no reflection
 *
 * Compatible with PHP 5.3.29.
 */
class Container implements ContainerInterface
{
    /**
     * Compiled factories from the dumped file, keyed by id.
     *
     * @var \Closure[]
     */
    private $factories = array();

    /**
     * Cache of already-built instances, keyed by id (every entry is shared).
     *
     * @var array
     */
    private $instances = array();

    /**
     * Register a compiled factory. This is what the file generated by the
     * Dumper calls; you normally never call it by hand.
     *
     * @param string   $id
     * @param \Closure $factory Receives the container, returns the built bean.
     * @return Container $this, for chaining.
     */
    public function register($id, \Closure $factory)
    {
        $this->factories[$id] = $factory;

        return $this;
    }

    /**
     * Retrieve an entry by its id. Everything — beans and parameters alike —
     * comes from a compiled factory, built once and cached. The container never
     * instantiates from a Definition; compile and loadCompiled() first.
     *
     * @param string $id
     * @return mixed
     * @throws NotFoundException  If nothing is registered for $id.
     * @throws ContainerException If the factory itself throws.
     */
    public function get($id)
    {
        if (array_key_exists($id, $this->instances)) {
            return $this->instances[$id];
        }

        if (isset($this->factories[$id])) {
            $factory = $this->factories[$id];

            return $this->instances[$id] = $factory($this);
        }

        throw new NotFoundException(sprintf('No entry registered for "%s".', $id));
    }

    /**
     * Whether the container can resolve the id (a compiled factory or an
     * already-built instance). Per PSR-11, true means get() will not throw a
     * NotFoundException.
     *
     * @param string $id
     * @return bool
     */
    public function has($id)
    {
        return isset($this->factories[$id])
            || array_key_exists($id, $this->instances);
    }

    /**
     * Drop everything registered for the given id.
     *
     * @param string $id
     * @return Container $this, for chaining.
     */
    public function remove($id)
    {
        unset(
            $this->factories[$id],
            $this->instances[$id]
        );

        return $this;
    }

    /**
     * All known ids (the registered factories).
     *
     * @return string[]
     */
    public function keys()
    {
        return array_keys($this->factories);
    }
}
